### ISSUE TITLE
Autonomous via CommandGroup/Scheduler

### ISSUE THREAD

**Issue by dchao19** [teamkomodo/Robot-2017#1]
We should figure out if the Autonomous routine needs to be a CommandGroup or run via the Scheduler.

My understanding is that you can run a CommandGroup without the Scheduler and that the Scheduler should only be used for running commands in Teleop control mode. 

But I also could be totally wrong so I'm just opening this issue for discussion purposes.

**Comment by BertrandTheHealer** [comment]
You can run a Command Group without the Scheduler. That's what the code does right now.
